BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE member_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE member_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE member CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE member (
    id NUMBER(19) PRIMARY KEY,
    loginId VARCHAR2(15 CHAR),
    nickname VARCHAR2(15 CHAR),
    password VARCHAR2(60 CHAR),
    role VARCHAR2(10 CHAR)
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE product_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE product_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE product CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE product (
    id NUMBER(19) PRIMARY KEY,
    memberId NUMBER(19),
    name VARCHAR2(100 CHAR),
    price NUMBER(10),
    description VARCHAR2(2000 CHAR),
    stockQuantity NUMBER(10) NOT NULL,
    createdAt TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_product_member FOREIGN KEY (memberId) REFERENCES member(id) ON DELETE CASCADE
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE orders_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE orders_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE orders (
    id NUMBER(19) PRIMARY KEY,
    memberId NUMBER(19),
    orderDate TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(10 CHAR) DEFAULT 'PAID',
    totalPrice NUMBER(10),
    CONSTRAINT fk_orders_member FOREIGN KEY (memberId) REFERENCES member(id) ON DELETE CASCADE
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE orderProduct_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE orderProduct_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE orderProduct CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE orderProduct (
    id NUMBER(19) PRIMARY KEY,
    orderId NUMBER(19),
    productId NUMBER(19),
    productName VARCHAR2(100 CHAR),
    price NUMBER(10),
    quantity NUMBER(10),
    CONSTRAINT fk_orderProduct_orders FOREIGN KEY (orderId) REFERENCES orders(id) ON DELETE CASCADE,
    CONSTRAINT fk_orderProduct_product FOREIGN KEY (productId) REFERENCES product(id) ON DELETE CASCADE
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE cart_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE cart_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE cart CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE cart (
    id NUMBER(19) PRIMARY KEY,
    memberId NUMBER(19),
    CONSTRAINT fk_cart_member FOREIGN KEY (memberId) REFERENCES member(id) ON DELETE CASCADE
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE cartItem_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE cartItem_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE cartItem CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE cartItem (
    id NUMBER(19) PRIMARY KEY,
    cartId NUMBER(19),
    productId NUMBER(19),
    productName VARCHAR2(100 CHAR),
    price NUMBER(10),
    quantity NUMBER(10) NOT NULL,
    CONSTRAINT fk_cartItem_cart FOREIGN KEY (cartId) REFERENCES cart(id) ON DELETE CASCADE,
    CONSTRAINT fk_cartItem_product FOREIGN KEY (productId) REFERENCES product(id) ON DELETE CASCADE
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE review_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE review_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE review CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE review (
    id NUMBER(19) PRIMARY KEY,
    memberId NUMBER(19),
    productId NUMBER(19),
    content VARCHAR2(100 CHAR),
    rating NUMBER(3,2),
    createdAt TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_review_member FOREIGN KEY (memberId) REFERENCES member(id) ON DELETE CASCADE,
    CONSTRAINT fk_review_product FOREIGN KEY (productId) REFERENCES product(id) ON DELETE CASCADE
)
/