BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE member_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE member_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE member CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE member (
    id NUMBER(19) PRIMARY KEY,
    loginId VARCHAR2(15 CHAR),
    nickname VARCHAR2(15 CHAR),
    password VARCHAR2(60 CHAR)
)
/