BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE member_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE member_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE member CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE member (
    id NUMBER(19) PRIMARY KEY,
    loginId VARCHAR2(15 CHAR),
    nickname VARCHAR2(15 CHAR),
    password VARCHAR2(60 CHAR),
    role VARCHAR2(10 CHAR)
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE product_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE product_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE product CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE product (
    id NUMBER(19) PRIMARY KEY,
    memberId NUMBER(19),
    name VARCHAR2(100 CHAR),
    price NUMBER(10),
    description VARCHAR2(2000 CHAR),
    stockQuantity NUMBER(10) DEFAULT 0,
    createdAt TIMESTAMP DEFAULT SYSTIMESTAMP,
    CONSTRAINT fk_product_member FOREIGN KEY (memberId) REFERENCES member(id) ON DELETE CASCADE
)
/

BEGIN
  EXECUTE IMMEDIATE 'DROP SEQUENCE orders_seq';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -2289 THEN RAISE; END IF;
END;
/

CREATE SEQUENCE orders_seq START WITH 1 INCREMENT BY 1
/

BEGIN
  EXECUTE IMMEDIATE 'DROP TABLE orders CASCADE CONSTRAINTS';
EXCEPTION
  WHEN OTHERS THEN
    IF SQLCODE != -942 THEN RAISE;
    END IF;
END;
/

CREATE TABLE orders (
    id NUMBER(19) PRIMARY KEY,
    memberId NUMBER(19),
    orderDate TIMESTAMP DEFAULT SYSTIMESTAMP,
    status VARCHAR2(10 CHAR) DEFAULT 'PENDING',
    totalPrice NUMBER(10),
    CONSTRAINT fk_orders_member FOREIGN KEY (memberId) REFERENCES member(id) ON DELETE CASCADE
)
/